name: Push to Registries

on:
  push:
    branches: [ main ]
    tags: ['*']
    
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile.cli      # variant X
            suffix: cli
          - dockerfile: Dockerfile.gradio      # variant Y
            suffix: gradio
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ github.repository_owner }}/${{ github.event.repository.name }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ matrix.suffix != '' && (matrix.suffix + '-' + steps.meta.outputs.version) || steps.meta.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ matrix.suffix != '' && (matrix.suffix + '-latest') || 'latest' }}
            ${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ matrix.suffix != '' && (matrix.suffix + '-' + steps.meta.outputs.version) || steps.meta.outputs.version }}
            ${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ matrix.suffix != '' && (matrix.suffix + '-latest') || 'latest' }}