# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "sunday"
      time: "12:00"


  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"
    groups:
      python-packages:
        patterns:
          - "ffmpeg-normalize"
          - "gradio"